package router

import (
	"net/http"

	"lws/internal/services"
)

// NewRouter builds the full request-dispatch table for lws, wiring every
// emulated AWS operation to its handler on the given service engine.
func NewRouter(eng *services.Engine) http.Handler {
	mux := NewMultiplexer()

	// Textract (JSON protocol)
	mux.RegisterJSONAction("Textract.DetectDocumentText", eng.TextractHandler.HandleDetectDocumentText)
	mux.RegisterJSONAction("Textract.AnalyzeDocument", eng.TextractHandler.HandleAnalyzeDocument)
	mux.RegisterJSONAction("Textract.AnalyzeExpense", eng.TextractHandler.HandleAnalyzeExpense)
	mux.RegisterJSONAction("Textract.StartDocumentTextDetection", eng.TextractHandler.HandleStartDocumentTextDetection)
	mux.RegisterJSONAction("Textract.GetDocumentTextDetection", eng.TextractHandler.HandleGetDocumentTextDetection)
	mux.RegisterJSONAction("Textract.StartDocumentAnalysis", eng.TextractHandler.HandleStartDocumentAnalysis)
	mux.RegisterJSONAction("Textract.GetDocumentAnalysis", eng.TextractHandler.HandleGetDocumentAnalysis)
	mux.RegisterJSONAction("Textract.AnalyzeID", eng.TextractHandler.HandleAnalyzeID)
	mux.RegisterJSONAction("Textract.StartExpenseAnalysis", eng.TextractHandler.HandleStartExpenseAnalysis)
	mux.RegisterJSONAction("Textract.GetExpenseAnalysis", eng.TextractHandler.HandleGetExpenseAnalysis)
	mux.RegisterJSONAction("Textract.StartLendingAnalysis", eng.TextractHandler.HandleStartLendingAnalysis)
	mux.RegisterJSONAction("Textract.GetLendingAnalysis", eng.TextractHandler.HandleGetLendingAnalysis)
	mux.RegisterJSONAction("Textract.GetLendingAnalysisSummary", eng.TextractHandler.HandleGetLendingAnalysisSummary)
	mux.RegisterJSONAction("Textract.CreateAdapter", eng.TextractHandler.HandleCreateAdapter)
	mux.RegisterJSONAction("Textract.GetAdapter", eng.TextractHandler.HandleGetAdapter)
	mux.RegisterJSONAction("Textract.UpdateAdapter", eng.TextractHandler.HandleUpdateAdapter)
	mux.RegisterJSONAction("Textract.DeleteAdapter", eng.TextractHandler.HandleDeleteAdapter)
	mux.RegisterJSONAction("Textract.ListAdapters", eng.TextractHandler.HandleListAdapters)
	mux.RegisterJSONAction("Textract.CreateAdapterVersion", eng.TextractHandler.HandleCreateAdapterVersion)
	mux.RegisterJSONAction("Textract.GetAdapterVersion", eng.TextractHandler.HandleGetAdapterVersion)
	mux.RegisterJSONAction("Textract.DeleteAdapterVersion", eng.TextractHandler.HandleDeleteAdapterVersion)
	mux.RegisterJSONAction("Textract.ListAdapterVersions", eng.TextractHandler.HandleListAdapterVersions)
	mux.RegisterJSONAction("Textract.TagResource", eng.TextractHandler.HandleTagResource)
	mux.RegisterJSONAction("Textract.UntagResource", eng.TextractHandler.HandleUntagResource)
	mux.RegisterJSONAction("Textract.ListTagsForResource", eng.TextractHandler.HandleListTagsForResource)

	// SQS (Query protocol)
	mux.RegisterQueryAction("CreateQueue", eng.SQSHandler.HandleCreateQueue)
	mux.RegisterQueryAction("GetQueueUrl", eng.SQSHandler.HandleGetQueueUrl)
	mux.RegisterQueryAction("SendMessage", eng.SQSHandler.HandleSendMessage)
	mux.RegisterQueryAction("ReceiveMessage", eng.SQSHandler.HandleReceiveMessage)
	mux.RegisterQueryAction("DeleteMessage", eng.SQSHandler.HandleDeleteMessage)
	mux.RegisterQueryAction("DeleteQueue", eng.SQSHandler.HandleDeleteQueue)
	mux.RegisterQueryAction("ListQueues", eng.SQSHandler.HandleListQueues)
	mux.RegisterQueryAction("ChangeMessageVisibility", eng.SQSHandler.HandleChangeMessageVisibility)
	mux.RegisterQueryAction("ChangeMessageVisibilityBatch", eng.SQSHandler.HandleChangeMessageVisibilityBatch)
	mux.RegisterQueryAction("DeleteMessageBatch", eng.SQSHandler.HandleDeleteMessageBatch)
	mux.RegisterQueryAction("SendMessageBatch", eng.SQSHandler.HandleSendMessageBatch)
	mux.RegisterQueryAction("PurgeQueue", eng.SQSHandler.HandlePurgeQueue)
	mux.RegisterQueryAction("GetQueueAttributes", eng.SQSHandler.HandleGetQueueAttributes)
	mux.RegisterQueryAction("SetQueueAttributes", eng.SQSHandler.HandleSetQueueAttributes)
	mux.RegisterQueryAction("TagQueue", eng.SQSHandler.HandleTagQueue)
	mux.RegisterQueryAction("UntagQueue", eng.SQSHandler.HandleUntagQueue)
	mux.RegisterQueryAction("ListQueueTags", eng.SQSHandler.HandleListQueueTags)
	mux.RegisterQueryAction("AddPermission", eng.SQSHandler.HandleAddPermission)
	mux.RegisterQueryAction("RemovePermission", eng.SQSHandler.HandleRemovePermission)
	mux.RegisterQueryAction("ListDeadLetterSourceQueues", eng.SQSHandler.HandleListDeadLetterSourceQueues)
	mux.RegisterQueryAction("StartMessageMoveTask", eng.SQSHandler.HandleStartMessageMoveTask)
	mux.RegisterQueryAction("ListMessageMoveTasks", eng.SQSHandler.HandleListMessageMoveTasks)
	mux.RegisterQueryAction("CancelMessageMoveTask", eng.SQSHandler.HandleCancelMessageMoveTask)

	// SQS (JSON protocol) - current AWS SDKs default to this over Query.
	mux.RegisterJSONAction("AmazonSQS.CreateQueue", eng.SQSHandler.HandleCreateQueueJSON)
	mux.RegisterJSONAction("AmazonSQS.GetQueueUrl", eng.SQSHandler.HandleGetQueueUrlJSON)
	mux.RegisterJSONAction("AmazonSQS.SendMessage", eng.SQSHandler.HandleSendMessageJSON)
	mux.RegisterJSONAction("AmazonSQS.ReceiveMessage", eng.SQSHandler.HandleReceiveMessageJSON)
	mux.RegisterJSONAction("AmazonSQS.DeleteMessage", eng.SQSHandler.HandleDeleteMessageJSON)
	mux.RegisterJSONAction("AmazonSQS.DeleteQueue", eng.SQSHandler.HandleDeleteQueueJSON)
	mux.RegisterJSONAction("AmazonSQS.ListQueues", eng.SQSHandler.HandleListQueuesJSON)
	mux.RegisterJSONAction("AmazonSQS.ChangeMessageVisibility", eng.SQSHandler.HandleChangeMessageVisibilityJSON)
	mux.RegisterJSONAction("AmazonSQS.ChangeMessageVisibilityBatch", eng.SQSHandler.HandleChangeMessageVisibilityBatchJSON)
	mux.RegisterJSONAction("AmazonSQS.DeleteMessageBatch", eng.SQSHandler.HandleDeleteMessageBatchJSON)
	mux.RegisterJSONAction("AmazonSQS.SendMessageBatch", eng.SQSHandler.HandleSendMessageBatchJSON)
	mux.RegisterJSONAction("AmazonSQS.PurgeQueue", eng.SQSHandler.HandlePurgeQueueJSON)
	mux.RegisterJSONAction("AmazonSQS.GetQueueAttributes", eng.SQSHandler.HandleGetQueueAttributesJSON)
	mux.RegisterJSONAction("AmazonSQS.SetQueueAttributes", eng.SQSHandler.HandleSetQueueAttributesJSON)
	mux.RegisterJSONAction("AmazonSQS.TagQueue", eng.SQSHandler.HandleTagQueueJSON)
	mux.RegisterJSONAction("AmazonSQS.UntagQueue", eng.SQSHandler.HandleUntagQueueJSON)
	mux.RegisterJSONAction("AmazonSQS.ListQueueTags", eng.SQSHandler.HandleListQueueTagsJSON)
	mux.RegisterJSONAction("AmazonSQS.AddPermission", eng.SQSHandler.HandleAddPermissionJSON)
	mux.RegisterJSONAction("AmazonSQS.RemovePermission", eng.SQSHandler.HandleRemovePermissionJSON)
	mux.RegisterJSONAction("AmazonSQS.ListDeadLetterSourceQueues", eng.SQSHandler.HandleListDeadLetterSourceQueuesJSON)
	mux.RegisterJSONAction("AmazonSQS.StartMessageMoveTask", eng.SQSHandler.HandleStartMessageMoveTaskJSON)
	mux.RegisterJSONAction("AmazonSQS.ListMessageMoveTasks", eng.SQSHandler.HandleListMessageMoveTasksJSON)
	mux.RegisterJSONAction("AmazonSQS.CancelMessageMoveTask", eng.SQSHandler.HandleCancelMessageMoveTaskJSON)

	// SNS (Query protocol)
	mux.RegisterQueryAction("CreateTopic", eng.SNSHandler.HandleCreateTopic)
	mux.RegisterQueryAction("DeleteTopic", eng.SNSHandler.HandleDeleteTopic)
	mux.RegisterQueryAction("ListTopics", eng.SNSHandler.HandleListTopics)
	mux.RegisterQueryAction("GetTopicAttributes", eng.SNSHandler.HandleGetTopicAttributes)
	mux.RegisterQueryAction("SetTopicAttributes", eng.SNSHandler.HandleSetTopicAttributes)
	mux.RegisterQueryAction("TagResource", eng.SNSHandler.HandleTagResource)
	mux.RegisterQueryAction("UntagResource", eng.SNSHandler.HandleUntagResource)
	mux.RegisterQueryAction("ListTagsForResource", eng.SNSHandler.HandleListTagsForResource)
	mux.RegisterQueryAction("AddPermission", eng.SNSHandler.HandleAddPermission)
	mux.RegisterQueryAction("RemovePermission", eng.SNSHandler.HandleRemovePermission)
	mux.RegisterQueryAction("Subscribe", eng.SNSHandler.HandleSubscribe)
	mux.RegisterQueryAction("ConfirmSubscription", eng.SNSHandler.HandleConfirmSubscription)
	mux.RegisterQueryAction("Unsubscribe", eng.SNSHandler.HandleUnsubscribe)
	mux.RegisterQueryAction("ListSubscriptionsByTopic", eng.SNSHandler.HandleListSubscriptionsByTopic)
	mux.RegisterQueryAction("ListSubscriptions", eng.SNSHandler.HandleListSubscriptions)
	mux.RegisterQueryAction("GetSubscriptionAttributes", eng.SNSHandler.HandleGetSubscriptionAttributes)
	mux.RegisterQueryAction("SetSubscriptionAttributes", eng.SNSHandler.HandleSetSubscriptionAttributes)
	mux.RegisterQueryAction("Publish", eng.SNSHandler.HandlePublish)
	mux.RegisterQueryAction("PublishBatch", eng.SNSHandler.HandlePublishBatch)

	// Secrets Manager (JSON protocol)
	mux.RegisterJSONAction("secretsmanager.CreateSecret", eng.SecretsManagerHandler.HandleCreateSecret)
	mux.RegisterJSONAction("secretsmanager.GetSecretValue", eng.SecretsManagerHandler.HandleGetSecretValue)
	mux.RegisterJSONAction("secretsmanager.PutSecretValue", eng.SecretsManagerHandler.HandlePutSecretValue)
	mux.RegisterJSONAction("secretsmanager.DescribeSecret", eng.SecretsManagerHandler.HandleDescribeSecret)
	mux.RegisterJSONAction("secretsmanager.ListSecrets", eng.SecretsManagerHandler.HandleListSecrets)
	mux.RegisterJSONAction("secretsmanager.DeleteSecret", eng.SecretsManagerHandler.HandleDeleteSecret)
	mux.RegisterJSONAction("secretsmanager.RestoreSecret", eng.SecretsManagerHandler.HandleRestoreSecret)
	mux.RegisterJSONAction("secretsmanager.UpdateSecret", eng.SecretsManagerHandler.HandleUpdateSecret)
	mux.RegisterJSONAction("secretsmanager.TagResource", eng.SecretsManagerHandler.HandleTagResource)
	mux.RegisterJSONAction("secretsmanager.UntagResource", eng.SecretsManagerHandler.HandleUntagResource)
	mux.RegisterJSONAction("secretsmanager.ListSecretVersionIds", eng.SecretsManagerHandler.HandleListSecretVersionIds)

	// S3 (REST protocol) - bucket/key in the URL path, dispatched by HTTP
	// method and query-string subresource rather than an Action/Target.
	mux.RegisterRESTFallback(eng.S3Handler)

	return mux
}
